[package]
name = "lnx-wal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
okaywal = { workspace = true }
lz4_flex = { workspace = true }