[package]
name = "lnx"
version = "0.1.0"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", featyres = ["server", "http1", "http2"] }
axum = "0.1.3"
structopt = "0.3"
tokio-rustls = "0.22"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
anyhow = "1"
chrono = "0.4"
num_cpus = "1.13"

engine = { path = "./engine" }