[workspace]
members = [
    "search-engine/engine",
    "search-engine/aexecutor",
    "search-engine/search-index",
    "lnx-server",
]
exclude = ["lnxcli"]

[profile.release]
lto = "fat"
codegen-units = 1