[package]
name = "lnx"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace.dependencies]
serde_json = "1"
smallvec = "1.10.0"
thiserror = "1"
anyhow = "1"
ryu = "1"
itoa = "1"
base64 = "0.21.2"
okaywal = "0.2.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
parking_lot = "0.12.1"
num_cpus = "1.15.0"
rayon = "1.7.0"
arc-swap = "1.6.0"
futures = "0.3.28"
cityhash-sys = "=1.0.2"
crc32fast = "1.3.2"

tokio = { version = "1.28.2", features = ["full"] }
heed = { version = "0.20.0-alpha.0", default-features = false }
bumpalo = { version = "3", features = ["collections"] }
time = { version = "0.3.21", features = ["parsing", "formatting"] }
serde = { version = "1", features = ["derive"] }
rkyv = { version = "0.7.42", features = ["strict", "validation"] }
lz4_flex = { version = "0.11", default-features = false, features = ["std"] }
datacake = { version = "0.7.1", git = "https://github.com/lnx-search/datacake.git" }

[workspace]
members = [
    "lnx-document",
    "lnx-transforms",
    "lnx-wal",
    "lnx-metastore",
    "lnx-executor",
    "lnx-tools",
    "lnx-replica",
]