name: Dockerize

on:
  push:
    branches: [ master ]

jobs:      
  dockerize:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[VERSION-BUMP]')"
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to docker
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chillfish8/lnx:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
