name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build main
      run: cargo build --verbose
    - name: Run Lint
      run: cargo fmt -- --check
    - name: Run Clippy
      run: cargo clippy -- -D warnings
    - name: Run main tests
      run: cargo test --release --verbose -- --test-threads 2         
